services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
    # ports:
      # - "3306:3306"

  mariadb:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - mariadb:/var/lib/mysql
    # ports:
      # - "3307:3306"

  postgresql:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  db-dumper:
    image: db-dumper:latest
    env_file: .env
    depends_on:
      - mysql
      - mariadb
      - postgresql
    ports:
      - "8000:8000"
    volumes:
      - ./db_dumps:/db_dumps
      - ./config.py:/app/config.py

volumes:
  mysql:
  mariadb:
  postgresql:
